name: MobMasks
main: en.twebor.mobmasks.MobMasks
description: A simple plugin to create mobmasks.
author: Twebor and Soferir
version: 1.0.0
website: github.com/twebor

commands:
  info:
    description: Gives the command info
    usage: /info

  skull:
    description: Gives a player a skull
    usage: /skull

  mobmasks:
    description: Base command for MobMasks
    usage: /mobmasks <help, give, info> <?>